version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: "@babel/runtime"
    versions:
    - 7.13.16
  - dependency-name: husky
    versions:
    - 5.1.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.8
