name: Pull Requests
on: pull_request
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install
        uses: Borales/actions-yarn@1.1.0
        with:
          args: install

      - name: Lint
        uses: Borales/actions-yarn@1.1.0
        with:
          args: lint

      - name: Test
        uses: Borales/actions-yarn@1.1.0
        with:
          args: test

      - name: Build
        uses: Borales/actions-yarn@1.1.0
        with:
          args: build

      - name: 'Test: smoke'
        uses: Borales/actions-yarn@1.1.0
        with:
          args: 'test:smoke'
